name: Go Lint on PR
on:
  pull_request_target:
    paths:
      - "*/**"
      - go.*
      - "!.github/**"
      - "!tmp/**"
jobs:
  golangci-lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR head
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0

      - name: Checkout current
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Merge PR into current
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git merge ${{ github.event.pull_request.head.sha }}

      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.IQSC_BOT_TOKEN }}
        run: git config --global url."https://iqsc-bot:${TOKEN}@github.com".insteadOf "https://github.com"

      - name: Lint
        uses: golangci/golangci-lint-action@v2
        with:
          args: --timeout=3m
